version: "3"

services:
  uhr:
    container_name: uhr
    image: AutoCheckInUESTC:latest
    volumes:
      - ./config.py:/app/server/config.py
    restart: on-failure
    stdin_open: true
    tty: true
    